/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribedRouteImport } from './routes/unsubscribed'
import { Route as SubscribedRouteImport } from './routes/subscribed'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as EngageRouteImport } from './routes/engage'
import { Route as IndexRouteImport } from './routes/index'

const UnsubscribedRoute = UnsubscribedRouteImport.update({
  id: '/unsubscribed',
  path: '/unsubscribed',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribedRoute = SubscribedRouteImport.update({
  id: '/subscribed',
  path: '/subscribed',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const EngageRoute = EngageRouteImport.update({
  id: '/engage',
  path: '/engage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/engage': typeof EngageRoute
  '/legal': typeof LegalRoute
  '/subscribed': typeof SubscribedRoute
  '/unsubscribed': typeof UnsubscribedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/engage': typeof EngageRoute
  '/legal': typeof LegalRoute
  '/subscribed': typeof SubscribedRoute
  '/unsubscribed': typeof UnsubscribedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/engage': typeof EngageRoute
  '/legal': typeof LegalRoute
  '/subscribed': typeof SubscribedRoute
  '/unsubscribed': typeof UnsubscribedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/engage' | '/legal' | '/subscribed' | '/unsubscribed'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/engage' | '/legal' | '/subscribed' | '/unsubscribed'
  id: '__root__' | '/' | '/engage' | '/legal' | '/subscribed' | '/unsubscribed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EngageRoute: typeof EngageRoute
  LegalRoute: typeof LegalRoute
  SubscribedRoute: typeof SubscribedRoute
  UnsubscribedRoute: typeof UnsubscribedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribed': {
      id: '/unsubscribed'
      path: '/unsubscribed'
      fullPath: '/unsubscribed'
      preLoaderRoute: typeof UnsubscribedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribed': {
      id: '/subscribed'
      path: '/subscribed'
      fullPath: '/subscribed'
      preLoaderRoute: typeof SubscribedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engage': {
      id: '/engage'
      path: '/engage'
      fullPath: '/engage'
      preLoaderRoute: typeof EngageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EngageRoute: EngageRoute,
  LegalRoute: LegalRoute,
  SubscribedRoute: SubscribedRoute,
  UnsubscribedRoute: UnsubscribedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
